algoritmo " pode triângulo "
var

 ladoA, ladoB, ladoC : real

inicio

Escreva("Digite o 1º lado: ")
leia(ladoA)
Escreva("Digite o 2º lado: ")
leia(ladoB)
Escreva("Digite o 3º lado: ")
leia(ladoC)


           Se (ladoA + ladoB > ladoC) e (ladoA + ladoC > ladoB) e (ladoB + ladoC > ladoA ) entao
              EscrevaL("Os lados formam um triângulo")
           SeNao
              EscrevaL("Os lados NÃO formam um triangulo")
           FimSe




fimalgoritmo